name: Compile PDF from LaTeX source

on:
  workflow_dispatch:
      inputs:
        tag:
          description: 'Tag Name'
          required: true
          default: 'v0.0.0'
          type: string
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
      - name: Create new release with resulting PDF
        uses: svenstaro/upload-release-action@v2
        with:
          file: thesis.pdf
          asset_name: thesis.pdf
          overwrite: true
          body: "Resulting PDF from last build of this LaTeX project ..."
          tag: ${{ inputs.tag }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        
