name: Compile PDF from LaTeX source

on:
  workflow_dispatch:
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Build LaTeX
        uses: dante-ev/latex-action@latest
        with:
          root_file: thesis.tex
      - name: Create new release with resulting PDF
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: thesis.pdf
        
